= Android library AAR package

. create `android` directory in project root
. start Android Studio and select `Start a new Android Studio project`
. select `Phone and Tablet` -> `Empty Activity` and click `Next`
. as name enter library name without `lib` prefix, as `Package name` enter unique package name, as `Save location` slect the newly created `android` directory, as `Language` select `Java`, as `Minimum SDK` select API 21, leave `Use legacy android.support libraries` unchecked, click `Finish`
. remove `android/.idea` directory and add the whole `android` directory to git
. click `File` -> `New` -> `New Module...`, select `Android Library`, click `Next`
. as `Module name` enter library name without `lib` prefix, click `Finish`, agree to add new files to git
. open file `android/build.gradle` and add `classpath 'com.ydq.android.gradle.build.tool:nativeBundle:1.0.6'` to `buildscript` -> `dependencies`, in the same clasue change android gradle plugin version to `3.4.2` as build fails on `travic-ci.org` for some reason with later versions of the plugin
. open file `android/<library-name>/build.gradle` file
. add lines `apply plugin: 'com.ydq.android.gradle.native-aar.export' // must go after android gradle plugin` and `apply plugin: 'com.ydq.android.gradle.native-aar.import' // must go after android gradle plugin` right after the first line which imports android plugin
