= WIP: How to pack a C++ library for cocoapods

. create `xcode` directory in project root
. create `cocoapods` directory in project root
. run `Xcode` and and create a new project
.. as a template for the new project select `ios`/`Static Library`
.. click `Next`
.. as `Product Name` enter the library name **without** `lib` prefix
.. fill `Organization Name` and `Organization Identifier` fields
.. as `Language` select `Objective-C`
.. click `Next`
.. select the newly created `xcode` directory as project location
.. click `Create`
.. remove the dummy source files added by `Xcode`
... in the project files navigator, right-click on the folder containing dummy sources
... click `Delete`
... click `Move To Trash`
.. remove overriding of linker flags to suppress cocoapods warning about `OTHER_LDFLAGS` later
... in the project files navigator, select library name with blue icon
... select `Build Settings`
... in search field enter `other linker flags`
... edit the `Other Linker Flags` settings for both `Release` and `Debug`, set it to $(inherited)
.. remove `catalyst` support
... in the project files navigator, select library name with blue icon
... select `Build Settings`
... in search field enter `catalyst`
... set `Supports Mac Catalyst` setting to `No`
.. set deployment target to `iOS 8.0` to support both `armv7` and `arm64` architectures
... in the project files navigator, select library name with blue icon
... select `Build Settings`
... in search field enter `ios deployment target`
... set `iOS Deployment Target` setting to `iOS 8.0`
. close the `Xcode`
. copy the `Podfile` template to `xcode` directory and edit it accordingly
. add the whole `xcode` directory to git and possibly make a commit. After that it is safe to go to `xcode` directory and run `pod install`
. configure automatic adding of source to the project. This is needed because `Xcode` is unable to pick all sources from specific directory, so we use side tool for just adding all sources from directory to `Xcode` project.
.. add `ios` conditional script to `before_script:` section of `.travis-ci.yml`:

  before_script:
- if [ "$TRAVIS_JOB_NAME" == "ios" ]; then
    curl -L https://github.com/zackslash/Xcode-Proj-Adder/raw/master/bin/XcodeProjAdder -O &&
    chmod +x XcodeProjAdder &&
    (cd xcode/$PACKAGE_NAME && ../../XcodeProjAdder -XCP $PACKAGE_NAME.xcodeproj -SCSV `echo $(find ../../src -type f -name *.cpp) | sed -n -e 's/ /,/gp'`)
  fi

.. add `ios` conditional script to `script:` section of `.travis-ci.yml`:

  script:
- if [ "$TRAVIS_JOB_NAME" == "ios" ]; then
    xcodebuild -workspace xcode/$PACKAGE_NAME.xcworkspace -scheme $PACKAGE_NAME CONFIGURATION_BUILD_DIR=../build -configuration Release;
  fi

