= enable nuget repo

Packages are stored right on link:http://nuget.org[nuget.org], so you don't have to do anything special to setup the repo.

In **Visual Studio 2015+** right-click on project name in solution navigator panel and select `Manage NuGet Packages...`, install packages from there.

== note on VS2019+ and v142+ tools

For v142 tools the svgren library comes in 4 flavours of linking to a runtime library. Because of that, when using v142 tools (VS2019 or above) one needs to set also the runtime library in project master settings:

project properties (right click on project and select properties) -> Project Master Settings -> C/C++ Settings -> Runtime Library.

The value can be one of Multi-threaded, Multi-threaded Debug, Multi-threaded DLL, Multi-threaded Debug DLL. Set the same value is in your project properties -> C/C++ -> Code Generation -> Runtime Library.

If Project Master Settings / C/C++ Settings / Runtime Library is not set you will get linking errors when building your project.
