= Pack library to nuget package

. launch Visual Studio and click `Create a new project`
. select `Empty Project` as project template and click `Next`
. as `Project name` enter library name with `lib` prefix, as `Location` enter path to the project repository root directory, as `Solution name` enter `msvs_solution`
. make sure that `Place solution and project in the same directory` checkbox is `unchecked` and click `Create`
. in the project navigator panel right-click the `Source Files` folder and selct `Add`->`Existing Item...`
. select some library `.cpp` files and click `Add`
. click `Save All` button or use keyboard shortcut `Ctrl+Shift+s`
. add the whole `msvs_solution` directory to git
. in the project navigator panel right-click the library project name and select `Manage NuGet Packages...`
. install needed dependency nuget packages
. click `Save All` button or use keyboard shortcut `Ctrl+Shift+s`
. add the `msvs_solution/lib<name>/packages.config` file to git
. open the `msvs_solution/lib<name>/lib<name>.vcxproj` file in the text editor
. search for
`<ItemGroup><ClCompile Include="........"/>...</ItemGroup>` and change it to include all `.cpp` files, like this `<ItemGroup><ClCompile Include="..\..\src\**\*.cpp"/></ItemGroup>`
. TODO
