---
- hosts: all
  vars:
    pulp_settings:
      secret_key: <secret-key>
      content_origin: "https://cppfw.hopto.org"
    pulp_default_admin_password: pulp
    pulp_install_plugins:
      # galaxy-ng: {}
      # pulp-2to3-migration: {}
      # pulp-ansible: {}
      # pulp-certguard: {}
      pulp-container: {}
      # pulp-cookbook: {}
      pulp-deb: {}
      pulp-file: {}
      # pulp-gem: {}
      pulp-maven: {}
      # pulp-npm: {}
      # pulp-python: {}
      pulp-rpm:
        prereq_role: "pulp.pulp_rpm_prerequisites"

  # can be removed once this is resolved: https://pulp.plan.io/issues/8701
#  pre_tasks:
#    - name: install EPEL
#      yum:
#        name: epel-release
#      become: yes
  roles:
    - pulp.pulp_installer.pulp_all_services
  environment:
    DJANGO_SETTINGS_MODULE: pulpcore.app.settings
